[versions]
# libraries
devtools-common = "1.9.7-SNAPSHOT"

# plugins
gradleIntelliJPlugin = "2.1.0"
kotlinJvm = "2.0.20"

[libraries]
devtools-common = { group = "com.redhat.devtools.intellij", name = "intellij-common", version.ref = "devtools-common" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }